[package]
name = "bramble-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
rust-htslib = "1.0"
ahash = "0.8"
clap = { version = "4.5", features = ["derive"] }
coitrees = "0.4"
flume = "0.11"
indicatif = "0.18.3"
mimalloc = "0.1"
noodles = { version = "0.101", features = ["sam", "gff", "gtf", "fasta", "core"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
debug = true
